name: Build and Publish

on:
  pull_request:
    branches:
      - prod
    types:
      - closed
  workflow_dispatch:

jobs:
  call-build:
    uses: tylerpitcher/workflows/.github/workflows/build.yaml@main
    with:
      dockerfile_path: ./Dockerfile
      image_name: test
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
