name: Build, Publish, and Deploy

on:
  pull_request:
    branches:
      - main
    types:
      - closed
  workflow_dispatch:

jobs:
  build-and-publish:
    if: github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true
    uses: tylerpitcher/workflows/.github/workflows/build.yaml@main
    with:
      dockerfile_path: ./Dockerfile
      image_name: test
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  update-manifest:
    needs: build-and-publish
    if: github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true
    uses: tylerpitcher/workflows/.github/workflows/update.yaml@main
    with:
      yaml_file: manifests/test.yaml
      image_name: tylerpitcher/test
      image_version: ${{ github.sha }}
