name: Build and Publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  call-reusable-workflow:
    uses: tylerpitcher/workflows/.github/workflows/build.yaml@main
    with:
      dockerfile_path: ./Dockerfile
      image_name: test
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
